app = "bun-fun"
[[services]]
internal_port = 3000
protocol      = "tcp"

  [services.concurrency]
  hard_limit = 250
  soft_limit = 100
  type       = "requests"

  [[services.ports]]
  handlers = [ "http" ]
  port     = "80"

  [[services.ports]]
  handlers = [ "tls", "http" ]
  port     = "443"

  [[services.tcp_checks]]